### ISSUE TITLE
Plots issue

### ISSUE THREAD

**Issue by Csasaka19** [Csasaka19/R_credit#4]
The plots are not being seen after I added the Plotly library which is preferred for dynamic web content and shiny displays.

**Comment by eiidoubleyuwes** [comment]
I think  we might have to revert back to the old code because sielewi the documentation for plotly

**Comment by Csasaka19** [comment]
Yep my thought exactly 😮‍💨

**Comment by Csasaka19** [comment]
Fixed, there were some irrelevant lines of code that were clogging our dataset display
