### ISSUE TITLE
Fix the heatmap,it looks bad

### ISSUE THREAD

**Issue by eiidoubleyuwes** [Csasaka19/R_credit#5]
Change heatmap colors to red and make it look good,it looks crowded and not informative

@Eugene600 
@DeeMichere 
![Screenshot from 2023-11-27 16-55-05](https://github.com/Csasaka19/R_credit/assets/148796574/c8748bdf-a06b-4544-8f15-7d16dccb4f84)

**Comment by Eugene600** [comment]
Okay

**Comment by Csasaka19** [comment]
Seems they settled with green
